apiVersion: v2
name: cluster-api-provider-kairos
description: A Helm chart for the Kairos CAPI provider
icon: 
type: application
home: https://kairos.io/
maintainers:
- name: Ettore Di Giacinto
  email: mudler@kairos.io

version: 0.0.1
appVersion: "v0.0.1"